

	.FUNCT	TUNNEL-FORK-F,CONTEXT
	EQUAL?	CONTEXT,M-LOOK \FALSE
	ICALL1	SAY-CHAMBER
	CALL1	TO-N
	PRINT	STACK
	PRINTR	" and east, and there's a dark hole in the south wall."


	.FUNCT	SAY-CHAMBER
	PRINTI	"You're in a "
	CALL2	PICK-ONE,CRAMPS
	PRINT	STACK
	PRINTI	" under"
	PRINTD	GROUND
	PRINTI	" chamber. "
	RANDOM	100
	LESS?	50,STACK /?PRG8
	PRINTI	"Long"
	JUMP	?CND3
?PRG8:	PRINTI	"Cold"
?CND3:	RANDOM	100
	LESS?	50,STACK /?PRG14
	PRINTI	", "
	CALL2	PICK-ONE,CRAMPS
	PRINT	STACK
?PRG14:	PRINTI	" tunnels wander away "
	RTRUE	


	.FUNCT	INTO-GRAVE
	CALL2	CANT-FIT-INTO?,STR?204
	ZERO?	STACK \FALSE
	ICALL	MOVE-ALL,OPEN-GRAVE,INSIDE-GRAVE
	RETURN	INSIDE-GRAVE


	.FUNCT	TUNNEL-CORNER-F,CONTEXT
	EQUAL?	CONTEXT,M-LOOK \FALSE
	ICALL1	SAY-CHAMBER
	CALL1	TO-S
	PRINT	STACK
	PRINTR	", east and west."


	.FUNCT	ENTER-GRUE-NEST
	ZERO?	GRUE-COVERED? \?CND1
	CALL2	ENABLED?,I-GRUE-SLEEP
	ZERO?	STACK \?CND1
	SET	'SLEEP-SCRIPT,0
	CALL	QUEUE,I-GRUE-SLEEP,-1
	PUT	STACK,0,1
?CND1:	RETURN	GRUE-NEST


	.FUNCT	UNDER-HILL-F,CONTEXT
	EQUAL?	CONTEXT,M-LOOK \FALSE
	ICALL1	SAY-CHAMBER
	CALL1	TO-S
	PRINT	STACK
	PRINTI	" and east.

The surrounding walls are almost obscured by the roots of a mighty tree. "
	FSET?	STUMP,OPENBIT \?PRG11
	PRINTI	"Feeble light streams in from an opening overhead"
	JUMP	?PRG13
?PRG11:	PRINTI	"Overhead you can see the underside of a large "
	PRINTD	STUMP
	PRINTI	". It appears to be hinged"
?PRG13:	PRINTR	"."


	.FUNCT	EXIT-NEST
	DEC	'SLEEP-SCRIPT
	RETURN	TUNNEL-CORNER


	.FUNCT	GRUE-NEST-F,CONTEXT
	EQUAL?	CONTEXT,M-LOOK \FALSE
	PRINTI	"You have stumbled into the nesting place of a family of grues. Congratulations. Few indeed are the adventurers who have entered a grue's nest and lived as long as you have.

Everything is littered with rusty swords of elvish workmanship, piles of bones and other debris. A"
	ICALL	OPEN-CLOSED,REFRIGERATOR,TRUE-VALUE
	PRINTD	REFRIGERATOR
	PRINTI	" stands in one "
	PRINTD	CORNER
	PRINTI	" of the nest, and something"
	IN?	BLANKET,BABY \?PRG13
	PRINTI	" is curled up under a "
	PRINTD	BLANKET
	JUMP	?PRG15
?PRG13:	PRINTI	"... a small, dangerous-looking "
	PRINTD	BABY
	PRINTI	"... is curled up"
?PRG15:	PRINTI	" in the other "
	PRINTD	CORNER
	PRINTR	".

The only exit is to the west. Hope you survive long enough to use it."


	.FUNCT	BABY-F,CONTEXT
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	ICALL2	SAY-THE,BABY
	PRINTI	" is "
	IN?	BLANKET,BABY \?PRG11
	PRINTI	"covered with a "
	PRINTD	BLANKET
	JUMP	?PRG13
?PRG11:	PRINTI	"dressed in swaddling clothes with a pink baby bonnet, has long, slavering fangs and appears to be sleeping"
?PRG13:	PRINTR	"."
?CCL3:	EQUAL?	PRSA,V?REPLY,V?HELLO,V?TELL /?PRD18
	EQUAL?	PRSA,V?ASK-ABOUT,V?YELL,V?ALARM /?PRD18
	EQUAL?	PRSA,V?QUESTION,V?ASK-FOR \?CCL16
?PRD18:	EQUAL?	PRSO,BABY \?CCL16
	ICALL2	WAKE-BABY,STR?303
	RETURN	2
?CCL16:	EQUAL?	PRSA,V?THROW,V?PUT-ON,V?PUT /?PRD27
	EQUAL?	PRSA,V?THROW-OFF \?CCL25
?PRD27:	EQUAL?	PRSI,BABY \?CCL25
	EQUAL?	PRSO,BLANKET \?CCL32
	ICALL1	COVER-GRUE
	RTRUE	
?CCL32:	ICALL1	WAKE-BABY
	RTRUE	
?CCL25:	EQUAL?	PRSA,V?HIDE \?CCL34
	EQUAL?	PRSO,BABY \?CCL34
	ZERO?	PRSI /?CCL34
	EQUAL?	PRSI,BLANKET \?CCL40
	ICALL1	COVER-GRUE
	RTRUE	
?CCL40:	ICALL	PERFORM,V?PUT-ON,PRSI,BABY
	RTRUE	
?CCL34:	EQUAL?	PRSA,V?KISS \?CCL42
	ICALL2	SAY-THE,BABY
	PRINTR	" smiles in its sleep."
?CCL42:	EQUAL?	PRSA,V?GIVE,V?FEED \?CCL46
	ICALL	YOUD-HAVE-TO,STR?304,BABY
	RTRUE	
?CCL46:	CALL2	TOUCHING?,BABY
	ZERO?	STACK /?CCL48
	ICALL1	WAKE-BABY
	RETURN	2
?CCL48:	EQUAL?	PRSA,V?LISTEN \FALSE
	ICALL2	SAY-THE,BABY
	PRINTR	" snores gently."


	.FUNCT	WAKE-BABY,REASON
	PRINTI	"Oh, no! "
	ZERO?	REASON /?PRG8
	PRINT	REASON
	JUMP	?PRG10
?PRG8:	PRINTI	"Your reckless fumbling"
?PRG10:	PRINTI	" woke up the "
	PRINTD	BABY
	PRINTI	"!

The little creature "
	ZERO?	LIT /?PRG17
	PRINTI	"blinks helplessly in the glow of"
	ICALL1	CANDLE-OR-STONE
	JUMP	?PRG19
?PRG17:	PRINTI	"gurgles angrily in the "
	PRINTD	DARKNESS
?PRG19:	PRINTC	46
	CALL1	MOTHER-COMES
	RSTACK	


	.FUNCT	MOTHER-COMES
	PRINTI	" It opens its slavering jaws and"
	ICALL1	SUBWAY
	CRLF	
	CRLF	
	ZERO?	LIT /?PRG8
	PRINTI	"A very large creature, equipped with slavering fangs and wearing a calico apron,"
	JUMP	?PRG10
?PRG8:	PRINTI	"Something very large"
?PRG10:	PRINTI	" lurks into the nest"
	ZERO?	LIT /?PRG17
	PRINTI	". Its mother instinct overcomes its overwhelming fear of light long enough to devour"
	JUMP	?PRG19
?PRG17:	PRINTI	" and devours"
?PRG19:	PRINTI	" you."
	CALL1	BAD-ENDING
	RSTACK	


	.FUNCT	SUBWAY
	PRINTI	" emits a hideous, plaintive wail that reminds you of a subway screeching to a halt."
	RTRUE	


	.FUNCT	COVER-GRUE
	SET	'GRUE-COVERED?,TRUE-VALUE
	CALL2	INT,I-GRUE-SLEEP
	PUT	STACK,0,0
	MOVE	BLANKET,BABY
	PRINT	OKAY
	PRINTI	"the "
	PRINTD	BABY
	PRINTI	" is now covered with the "
	PRINTD	BLANKET
	PRINTI	".

The creature stirs restlessly for an anxious moment. Then it settles into the comfortable "
	PRINTD	DARKNESS
	PRINTI	" of the "
	PRINTD	BLANKET
	PRINTI	", sighs gently and lies still."
	CRLF	
	CRLF	
	CALL2	UPDATE-SCORE,3
	RSTACK	


	.FUNCT	CANDLE-OR-STONE,OBJ
	IN?	CANDLE,PROTAGONIST /?CTR2
	IN?	CANDLE,HERE \?CCL3
?CTR2:	SET	'OBJ,CANDLE
	JUMP	?PRG6
?CCL3:	SET	'OBJ,WISHBRINGER
?PRG6:	PRINTC	32
	ICALL	ARTICLE,OBJ,TRUE-VALUE
	PRINTD	OBJ
	RTRUE	


	.FUNCT	I-GRUE-SLEEP
	ZERO?	FUZZY? \TRUE
	ZERO?	ECLIPSE? \TRUE
	EQUAL?	HERE,GRUE-NEST \FALSE
	ZERO?	LIT \?CCL10
	SET	'SLEEP-SCRIPT,0
	RTRUE	
?CCL10:	INC	'SLEEP-SCRIPT
	CRLF	
	EQUAL?	SLEEP-SCRIPT,1 \?CCL13
	PRINTI	"Snoring fitfully, the "
	PRINTD	BABY
	PRINTI	" turns away from the light of"
	ICALL1	CANDLE-OR-STONE
	PRINTR	" and faces the wall."
?CCL13:	EQUAL?	SLEEP-SCRIPT,2 \?PRG22
	ICALL2	SAY-THE,BABY
	PRINTR	" is stirring restlessly. It looks as if it's about to wake up!"
?PRG22:	PRINTI	"With a toothy yawn, the "
	PRINTD	BABY
	PRINTI	" opens its big red eyes and blinks at you with surprise and fear."
	CALL1	MOTHER-COMES
	RSTACK	


	.FUNCT	REFRIGERATOR-F
	EQUAL?	PRSA,V?READ,V?LOOK-ON,V?EXAMINE \?CCL3
	PRINTI	"A label on the "
	PRINTD	REFRIGERATOR
	PRINTI	" reads, """
	ICALL2	FROBOZZ,STR?305
	PRINTR	"."""
?CCL3:	EQUAL?	PRSA,V?OPEN \?CCL9
	FSET?	REFRIGERATOR,OPENBIT /?CCL9
	ICALL2	HANDLE-FRIDGE,STR?306
	RFALSE	
?CCL9:	EQUAL?	PRSA,V?CLOSE \?CCL13
	FSET?	REFRIGERATOR,OPENBIT \?CCL13
	ICALL2	HANDLE-FRIDGE,STR?307
	RFALSE	
?CCL13:	EQUAL?	PRSA,V?PUT-ON \?CCL17
	EQUAL?	PRSI,REFRIGERATOR \?CCL17
	ICALL1	NO-ROOM
	PRINTR	"It's covered with debris."
?CCL17:	CALL2	MOVING?,REFRIGERATOR
	ZERO?	STACK /?CCL23
	ICALL2	TOO-LARGE,REFRIGERATOR
	RTRUE	
?CCL23:	CALL2	HURT?,REFRIGERATOR
	ZERO?	STACK /FALSE
	PRINTI	"The owners"
	ICALL1	MIGHT-NOT-LIKE
	RTRUE	


	.FUNCT	HANDLE-FRIDGE,STR
	PRINTI	"A light inside the "
	PRINTD	REFRIGERATOR
	PRINT	STR
	PRINTI	" it."
	CRLF	
	CRLF	
	RTRUE	


	.FUNCT	BOTTLE-F,FULL?
	ICALL2	THIS-IS-IT,BOTTLE
	IN?	MILK,BOTTLE /?PRD1
	PUSH	0
	JUMP	?PRD2
?PRD1:	PUSH	1
?PRD2:	SET	'FULL?,STACK
	EQUAL?	PRSA,V?READ,V?LOOK-ON,V?EXAMINE \?CCL5
	PRINTI	"The words """
	ICALL2	FROBOZZ,STR?308
	PRINTI	""" are etched on the"
	ICALL2	OPEN-CLOSED,BOTTLE
	PRINTD	BOTTLE
	PRINTR	"."
?CCL5:	EQUAL?	PRSA,V?SEARCH,V?LOOK-DOWN,V?LOOK-INSIDE \?CCL13
	LOC	BOTTLE
	EQUAL?	STACK,HERE,PROTAGONIST /?PRG16
	ICALL	YOUD-HAVE-TO,STR?309,BOTTLE
	RTRUE	
?PRG16:	PRINTI	"There's "
	ZERO?	FULL? /?CCL20
	PRINTI	"a bit of "
	PRINTD	MILK
	JUMP	?PRG23
?CCL20:	ICALL2	PRINT-CONTENTS,BOTTLE
?PRG23:	PRINTI	" in the "
	PRINTD	BOTTLE
	PRINTR	"."
?CCL13:	EQUAL?	PRSA,V?DRINK-FROM,V?DRINK \?CCL26
	ZERO?	FULL? /?CCL29
	ICALL	PERFORM,V?DRINK,MILK
	RTRUE	
?CCL29:	ICALL1	BOTTLE-EMPTY
	RTRUE	
?CCL26:	EQUAL?	PRSA,V?EMPTY,V?POUR \?CCL31
	ZERO?	FULL? /?CCL34
	ICALL	PERFORM,V?POUR,MILK
	RTRUE	
?CCL34:	ICALL1	BOTTLE-EMPTY
	RTRUE	
?CCL31:	EQUAL?	PRSA,V?SHAKE \?CCL36
	ZERO?	FULL? /?CCL39
	FSET?	BOTTLE,OPENBIT \?CCL42
	ICALL	PERFORM,V?POUR,MILK
	RTRUE	
?CCL42:	ICALL2	SAY-THE,MILK
	PRINTR	" doesn't look any better."
?CCL39:	ICALL1	BOTTLE-EMPTY
	RTRUE	
?CCL36:	EQUAL?	PRSA,V?PUT \?CCL46
	EQUAL?	PRSI,BOTTLE \?CCL46
	PRINTI	"The mouth of the "
	PRINTD	BOTTLE
	PRINTR	" is too narrow."
?CCL46:	EQUAL?	PRSA,V?CLOSE,V?OPEN \?CCL52
	CALL2	DONT-HAVE?,BOTTLE
	ZERO?	STACK \TRUE
?CCL52:	CALL2	HURT?,BOTTLE
	ZERO?	STACK /FALSE
	PRINTI	"Maybe you should read the "
	PRINTD	BOTTLE
	PRINTR	" first."


	.FUNCT	BOTTLE-EMPTY
	ICALL2	SAY-THE,BOTTLE
	PRINTR	" is empty."


	.FUNCT	ACCESS-MILK?
	IN?	MILK,BOTTLE /?CCL3
	ICALL1	BOTTLE-EMPTY
	RFALSE	
?CCL3:	FSET?	BOTTLE,OPENBIT /TRUE
	ICALL	YOUD-HAVE-TO,STR?80,BOTTLE
	RFALSE	


	.FUNCT	MILK-F
	EQUAL?	PRSA,V?LOOK-INSIDE,V?EXAMINE \?CCL3
	ICALL2	SAY-THE,MILK
	PRINTR	" is dark brown, with little icky things lurking in it."
?CCL3:	IN?	BOTTLE,PROTAGONIST /?CCL7
	ICALL	YOUD-HAVE-TO,STR?234,BOTTLE
	RTRUE	
?CCL7:	EQUAL?	PRSA,V?TASTE,V?DRINK-FROM,V?DRINK \?CCL9
	CALL1	ACCESS-MILK?
	ZERO?	STACK /TRUE
	REMOVE	MILK
	SET	'MILK-SCRIPT,4
	CALL	QUEUE,I-DRINK,-1
	PUT	STACK,0,1
	PRINTR	"Slurp! All gone."
?CCL9:	EQUAL?	PRSA,V?TAKE,V?EMPTY,V?POUR /?PRD17
	EQUAL?	PRSA,V?THROW,V?PUT-ON,V?PUT /?PRD17
	EQUAL?	PRSA,V?DROP \?CCL15
?PRD17:	EQUAL?	PRSO,MILK \?CCL15
	CALL1	ACCESS-MILK?
	ZERO?	STACK /TRUE
	REMOVE	MILK
	ICALL2	SAY-THE,MILK
	PRINTI	" splashes all over the place."
	CRLF	
	CALL2	ACCESSIBLE?,KITTY
	ZERO?	STACK /?CCL27
	FSET?	KITTY,RMUNGBIT /?CCL27
	CRLF	
	ICALL2	GIVE-MILK-TO-CAT,KITTY
	RTRUE	
?CCL27:	CALL2	ACCESSIBLE?,CHAOS
	ZERO?	STACK /TRUE
	CRLF	
	ICALL2	GIVE-MILK-TO-CAT,CHAOS
	RTRUE	
?CCL15:	EQUAL?	PRSA,V?GIVE,V?FEED \?CCL32
	EQUAL?	PRSO,MILK \?CCL32
	FSET?	PRSI,ACTORBIT \?CCL32
	ICALL	PERFORM,V?POUR,MILK
	RTRUE	
?CCL32:	EQUAL?	PRSA,V?SMELL \?CCL37
	CALL1	ACCESS-MILK?
	ZERO?	STACK /TRUE
	PRINTR	"The fumes make you queasy."
?CCL37:	EQUAL?	PRSA,V?SHAKE \?CCL43
	ICALL1	MEAN-BOTTLE
	ICALL	PERFORM,V?SHAKE,BOTTLE
	RTRUE	
?CCL43:	EQUAL?	PRSA,V?BITE,V?EAT \FALSE
	ICALL1	NOT-SOLID
	RTRUE	


	.FUNCT	MEAN-BOTTLE
	PRINT	I-ASSUME
	PRINTI	" the "
	PRINTD	BOTTLE
	PRINTI	".]"
	CRLF	
	CRLF	
	RTRUE	


	.FUNCT	I-DRINK
	DEC	'MILK-SCRIPT
	CRLF	
	EQUAL?	MILK-SCRIPT,3 \?CCL3
	PRINTR	"You can feel little icky things sliding down your throat."
?CCL3:	EQUAL?	MILK-SCRIPT,2 \?CCL7
	PRINTI	"(The "
	PRINTD	MILK
	PRINTI	" is lurking in your stomach."
	ICALL1	MAKE-IT-SNAPPY
	JUMP	?CND1
?CCL7:	EQUAL?	MILK-SCRIPT,1 \?CCL11
	PRINTI	"(The taste of the "
	PRINTD	MILK
	PRINTI	" is starting to wear off."
	ICALL1	HOLD-YOUR-PEACE
?CND1:	CRLF	
	RTRUE	
?CCL11:	SET	'MILK-SCRIPT,0
	CALL2	INT,I-DRINK
	PUT	STACK,0,0
	PRINTI	"(Thankfully, the icky taste of "
	PRINTD	MILK
	PRINTR	" is gone.)"


	.FUNCT	WORM-F
	EQUAL?	PRSA,V?TAKE \?CCL3
	EQUAL?	PRSO,WORM \?CCL3
	CALL1	V-TAKE
	ZERO?	STACK /TRUE
	CRLF	
	ICALL2	SAY-THE,WORM
	PRINTR	" squirms with annoyance at your touch."
?CCL3:	EQUAL?	PRSA,V?EXAMINE \?CCL11
	ICALL2	SAY-THE,WORM
	PRINTI	" is covered with nasty little bits of dirt and slime. It wriggles nervously"
	IN?	WORM,PROTAGONIST \?PRG18
	PRINTI	" in "
	PRINTD	HANDS
?PRG18:	PRINTR	" as you look at it."
?CCL11:	CALL2	TALKING-TO?,WORM
	ZERO?	STACK /?CCL21
	ICALL2	IT-IGNORES-YOU,WORM
	RETURN	2
?CCL21:	EQUAL?	PRSA,V?KISS,V?TASTE,V?EAT \FALSE
	EQUAL?	PRSO,WORM \FALSE
	PRINTR	"Yuck! You've got to be kidding."


	.FUNCT	DEBRIS-F
	EQUAL?	HERE,GRUE-NEST /?CCL3
	ICALL1	CANT-SEE-ANY
	RETURN	2
?CCL3:	CALL1	SEE-VERB?
	ZERO?	STACK /?CCL7
	PRINTI	"Aside from the ominous implications, you see nothing "
	CALL2	PICK-ONE,YAWNS
	PRINT	STACK
	PRINTI	" about the "
	PRINTD	DEBRIS
	PRINTR	"."
?CCL7:	ICALL2	YOU-DONT-NEED,DEBRIS
	RETURN	2


	.FUNCT	UNDER-CELL-F,CONTEXT
	EQUAL?	CONTEXT,M-LOOK \FALSE
	ICALL1	SAY-CHAMBER
	CALL1	TO-N
	PRINT	STACK
	PRINTI	" and west."
	CRLF	
	CRLF	
	FSET?	HIDDEN-HATCH,RMUNGBIT \?CCL8
	PRINTI	"A patch of freshly dried concrete is visible"
	JUMP	?PRG18
?CCL8:	FSET?	UNDER-CELL,ONBIT \?PRG16
	PRINTI	"Faint light is streaming in from a narrow hole"
	JUMP	?PRG18
?PRG16:	PRINTI	"A dark, narrow hole is visible"
?PRG18:	PRINTR	" overhead."

	.ENDI
